Repository JohnFTitor/catalog-of-stuff, pull requests merged in 2022-04, with the labels that each got.

#17 Set Up Files
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/linters.yml
  .github/workflows/tests.yml
  .gitignore
  .rubocop.yml
  Gemfile
  Gemfile.lock
  src/classes/app.rb
  src/json/data.json
  src/main.rb
  src/spec/app_spec.rb
Labels: documentation

#18 Feature/item
  Gemfile
  src/classes/app.rb
  src/classes/item.rb
  src/main.rb
  src/spec/app_spec.rb
  src/spec/item_spec.rb
Labels: test, create feature

#22 Feature/music class
  src/classes/music.rb
  src/spec/music_spec.rb
Labels: test, create feature

#23 Feature/label
  src/classes/label.rb
  src/spec/label_spec.rb
Labels: test, create feature

#24 Genre Class
  src/classes/genre.rb
  src/spec/genre_spec.rb
Labels: test, create feature

#25 Feature/author
  src/classes/author.rb
  src/spec/author_spec.rb
Labels: test, create feature

#29 App Methods For MusicAlbum
  src/classes/app.rb
  src/classes/book_collection.rb
  src/classes/genre.rb
  src/classes/genre_collection.rb
  src/classes/item.rb
  src/classes/label.rb
  src/classes/label_collection.rb
  src/classes/music_collection.rb
  src/classes/type_collection.rb
  src/main.rb
  src/modules/common_checks.rb
  src/spec/genre_spec.rb
  src/spec/item_spec.rb
Labels: create feature

#28 Schema Book
  src/sql/schema.sql
Labels: create feature

#30 App Methods for Books
  src/classes/app.rb
  src/classes/book_collection.rb
  src/classes/item.rb
  src/classes/label.rb
  src/classes/label_collection.rb
  src/spec/item_spec.rb
  src/spec/label_spec.rb
Labels: create feature

#31 Feature/app game
  src/classes/app.rb
  src/classes/author.rb
  src/classes/author_collection.rb
  src/classes/game_collection.rb
  src/classes/item.rb
  src/spec/author_spec.rb
  src/spec/item_spec.rb
Labels: create feature

#34 Schema Music
  src/sql/schema.sql
Labels: create feature

#35 Documentation
  README.md
  catalog_of_my_things.png
  screenshot.gif
Labels: documentation

#36 Catalog Of Stuff V.1.0.0
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/linters.yml
  .github/workflows/tests.yml
  .gitignore
  .rubocop.yml
  Gemfile
  Gemfile.lock
  README.md
  catalog_of_my_things.png
  screenshot.gif
  src/classes/app.rb
  src/classes/author.rb
  src/classes/author_collection.rb
  src/classes/book.rb
  src/classes/book_collection.rb
  src/classes/game.rb
  src/classes/game_collection.rb
  src/classes/genre.rb
  src/classes/genre_collection.rb
  src/classes/item.rb
  src/classes/label.rb
  src/classes/label_collection.rb
  src/classes/music.rb
  src/classes/music_collection.rb
  src/classes/type_collection.rb
  src/main.rb
  src/modules/common_checks.rb
  src/modules/json_handler.rb
  src/modules/json_methods.rb
  src/spec/author_spec.rb
  src/spec/book_spec.rb
  src/spec/game_spec.rb
  src/spec/genre_spec.rb
  src/spec/item_spec.rb
  src/spec/label_spec.rb
  src/spec/music_spec.rb
  src/sql/schema.sql
Labels: documentation, test, create feature
